### ISSUE TITLE
Retrieve total amount of resources

### ISSUE THREAD

**Issue by tobbe-j** [aimeos/ai-admin-graphql#3]
When working with large amounts of resources some kind of pagination is needed to allow smaller requests. Currently, the graphql API supports the limit and offset parameters for doing pagination. 

However, to properly implement pagination the total amount of items is also required, to be able to allow the user to jump to the last page. This is currently not possible to query from the graphql API.

A possibly workaround is to use the REST admin API to query for this simple datapoint, but it would feel a lot easier to be able to query it together with the data from the graphql API.

**Comment by aimeos** [comment]
We want to retire the JSON admin API, so the GraphQL API needs that feature too. Guess, that would be necessary for all resource queries and also for lists sections within the queries. A possible solution could be to add a `total` property to that resources because we can't restructure the output to something like Laravel Lighthouse does now as it would be breaking.

**Comment by aimeos** [comment]
Implemented and available in 2024.x+: https://github.com/aimeos/ai-admin-graphql/commit/a0350c15d5e32522b8baab17d56de93c6e840ba4
